In [ ]:
!pip install --upgrade pandas

     |████████████████████████████████| 9.5MB 2.6MB/s 
  Found existing installation: pandas 1.1.2
    Uninstalling pandas-1.1.2:
      Successfully uninstalled pandas-1.1.2


In [ ]:
import pandas as pd
import numpy as np
pd.__version__

'1.1.3'

In [ ]:
pd.options.display.float_format = '{:.2f}'.format

In [ ]:
np.set_printoptions(precision=1)

In [ ]:
x1 = np.random.rand(2,5)*10
x1

array([[4.7, 1.1, 4.8, 4.2, 1.7],
       [8.6, 2.1, 3.8, 3.1, 1.4]])

In [ ]:
x2 = np.random.rand(2,5)*-1
x2

array([[-0.5, -0.8, -0.6, -0.8, -0.4],
       [-0.3, -0.7, -1. , -1. , -0.9]])

In [ ]:
np.concatenate([x1,x2])

array([[ 6.4,  0.1,  2.1,  8.7,  5.2],
       [ 1.6,  6. ,  7.7,  6.9,  0.8],
       [-0.3, -0.7, -0.4, -0.5, -0. ],
       [-0.1, -0.6, -0.2, -0.7, -0.7]])

In [ ]:
np.concatenate([x1,x2]).shape

(4, 5)

In [ ]:
np.concatenate([x1,x2], axis = 1)

array([[ 6.4,  0.1,  2.1,  8.7,  5.2, -0.3, -0.7, -0.4, -0.5, -0. ],
       [ 1.6,  6. ,  7.7,  6.9,  0.8, -0.1, -0.6, -0.2, -0.7, -0.7]])

In [ ]:
np.concatenate([x1,x2], axis = 1).shape

(2, 10)

In [ ]:
s1 = pd.Series(x1[0],index = ['a','b','c','d','e'])
s1

a   6.44
b   0.10
c   2.05
d   8.71
e   5.20
dtype: float64

In [ ]:
s2 = pd.Series(x2[0],index = ['c','d','e','f','g'])
s2

c   -0.34
d   -0.73
e   -0.38
f   -0.54
g   -0.04
dtype: float64

In [ ]:
pd.concat([s1,s2], axis=1)

0     1
a 6.44   nan
b 0.10   nan
c 2.05 -0.34
d 8.71 -0.73
e 5.20 -0.38
f  nan -0.54
g  nan -0.04

borrar los indices y crear nuevos, con drop=True borra indices repetidos

In [ ]:
s1.reset_index(drop=True)

0   6.44
1   0.10
2   2.05
3   8.71
4   5.20
dtype: float64

In [ ]:
pd.concat([s1.reset_index(drop=True),s2.reset_index(drop=True)], axis=1)

0     1
0 6.44 -0.34
1 0.10 -0.73
2 2.05 -0.38
3 8.71 -0.54
4 5.20 -0.04

In [ ]:
df1 = pd.DataFrame(np.random.rand(3,2)*10,columns=['a','b'])
df1

a    b
0 1.29 5.86
1 7.82 1.88
2 8.89 9.38

In [ ]:
df2 = pd.DataFrame(np.random.rand(3,2)*-1,columns=['a','b'], index = [2,3,4])
df2

a     b
2 -0.22 -0.92
3 -0.59 -0.36
4 -0.13 -0.91

In [ ]:
pd.concat([df1,df2])

a     b
0  1.29  5.86
1  7.82  1.88
2  8.89  9.38
2 -0.22 -0.92
3 -0.59 -0.36
4 -0.13 -0.91

In [ ]:
pd.concat([df1,df2], axis=1)

a    b     a     b
0 1.29 5.86   nan   nan
1 7.82 1.88   nan   nan
2 8.89 9.38 -0.22 -0.92
3  nan  nan -0.59 -0.36
4  nan  nan -0.13 -0.91

In [ ]:
pd.concat([df1,df2], axis=1, join='inner')

a    b     a     b
2 8.89 9.38 -0.22 -0.92

In [ ]:
pd.concat([
           df1.reset_index(drop=True),
           df2.reset_index(drop=True)
           ], axis=1)

a    b     a     b
0 1.29 5.86 -0.22 -0.92
1 7.82 1.88 -0.59 -0.36
2 8.89 9.38 -0.13 -0.91

In [ ]:
df1.append(df2).append(df2)

a     b
0  1.29  5.86
1  7.82  1.88
2  8.89  9.38
2 -0.22 -0.92
3 -0.59 -0.36
4 -0.13 -0.91
2 -0.22 -0.92
3 -0.59 -0.36
4 -0.13 -0.91

In [ ]:
df1.T

0    1    2
a 1.29 7.82 8.89
b 5.86 1.88 9.38

In [ ]:
df1.T.append(df2.T).T

a    b     a     b
0 1.29 5.86   nan   nan
1 7.82 1.88   nan   nan
2 8.89 9.38 -0.22 -0.92
3  nan  nan -0.59 -0.36
4  nan  nan -0.13 -0.91