In [1]:
!pip install --upgrade pandas

In [2]:
import pandas as pd
import numpy as np
pd.__version__

'1.3.5'

In [3]:
pd.options.display.float_format = '{:.2f}'.format

In [4]:
np.set_printoptions(precision=1)

In [5]:
x1 = np.random.rand(2,5)*10
x1

array([[6.6, 0.7, 8.5, 3.2, 6.8],
       [8.8, 4.3, 5.5, 9.1, 0.2]])

In [6]:
x2 = np.random.rand(2,5)*-1
x2

array([[-0.6, -0.8, -1. , -0.9, -0.9],
       [-0.8, -0.5, -0.5, -0.1, -0.1]])

In [7]:
np.concatenate([x1,x2])

array([[ 6.6,  0.7,  8.5,  3.2,  6.8],
       [ 8.8,  4.3,  5.5,  9.1,  0.2],
       [-0.6, -0.8, -1. , -0.9, -0.9],
       [-0.8, -0.5, -0.5, -0.1, -0.1]])

In [8]:
np.concatenate([x1,x2]).shape

(4, 5)

In [9]:
np.concatenate([x1,x2], axis = 1)

array([[ 6.6,  0.7,  8.5,  3.2,  6.8, -0.6, -0.8, -1. , -0.9, -0.9],
       [ 8.8,  4.3,  5.5,  9.1,  0.2, -0.8, -0.5, -0.5, -0.1, -0.1]])

In [10]:
np.concatenate([x1,x2], axis = 1).shape

(2, 10)

In [11]:
s1 = pd.Series(x1[0],index = ['a','b','c','d','e'])
s1

a   6.57
b   0.70
c   8.47
d   3.20
e   6.76
dtype: float64

In [12]:
s2 = pd.Series(x2[0],index = ['c','d','e','f','g'])
s2

c   -0.58
d   -0.83
e   -0.98
f   -0.87
g   -0.87
dtype: float64

In [13]:
pd.concat([s1,s2], axis=1)

0     1
a 6.57   NaN
b 0.70   NaN
c 8.47 -0.58
d 3.20 -0.83
e 6.76 -0.98
f  NaN -0.87
g  NaN -0.87

borrar los indices y crear nuevos, con drop=True borra indices repetidos

In [14]:
s1.reset_index(drop=True)

0   6.57
1   0.70
2   8.47
3   3.20
4   6.76
dtype: float64

In [15]:
pd.concat([s1.reset_index(drop=True),s2.reset_index(drop=True)], axis=1)

0     1
0 6.57 -0.58
1 0.70 -0.83
2 8.47 -0.98
3 3.20 -0.87
4 6.76 -0.87

In [16]:
df1 = pd.DataFrame(np.random.rand(3,2)*10,columns=['a','b'])
df1

a    b
0 9.84 0.81
1 8.07 1.44
2 3.03 9.60

In [17]:
df2 = pd.DataFrame(np.random.rand(3,2)*-1,columns=['a','b'], index = [2,3,4])
df2

a     b
2 -0.02 -0.52
3 -0.37 -0.38
4 -0.25 -0.57

In [18]:
pd.concat([df1,df2])

a     b
0  9.84  0.81
1  8.07  1.44
2  3.03  9.60
2 -0.02 -0.52
3 -0.37 -0.38
4 -0.25 -0.57

In [19]:
pd.concat([df1,df2], axis=1)

a    b     a     b
0 9.84 0.81   NaN   NaN
1 8.07 1.44   NaN   NaN
2 3.03 9.60 -0.02 -0.52
3  NaN  NaN -0.37 -0.38
4  NaN  NaN -0.25 -0.57

In [20]:
pd.concat([df1,df2], axis=1, join='inner')

a    b     a     b
2 3.03 9.60 -0.02 -0.52

In [21]:
pd.concat([
           df1.reset_index(drop=True),
           df2.reset_index(drop=True)
           ], axis=1)

a    b     a     b
0 9.84 0.81 -0.02 -0.52
1 8.07 1.44 -0.37 -0.38
2 3.03 9.60 -0.25 -0.57

In [22]:
df1.append(df2).append(df2)

a     b
0  9.84  0.81
1  8.07  1.44
2  3.03  9.60
2 -0.02 -0.52
3 -0.37 -0.38
4 -0.25 -0.57
2 -0.02 -0.52
3 -0.37 -0.38
4 -0.25 -0.57

In [23]:
df1.T

0    1    2
a 9.84 8.07 3.03
b 0.81 1.44 9.60

In [24]:
df1.T.append(df2.T).T

a    b     a     b
0 9.84 0.81   NaN   NaN
1 8.07 1.44   NaN   NaN
2 3.03 9.60 -0.02 -0.52
3  NaN  NaN -0.37 -0.38
4  NaN  NaN -0.25 -0.57